language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

sudo: false

services:
  - elasticsearch
  - mysql

# sleep to wait for Elasticsearch init
before_install:
  - sleep 10
  - pip install --upgrade setuptools==49.6.0
  - pip install --upgrade pip==18.1
  - pip install -r "requirements.txt"
  - pip install flake8
  - pip install coveralls
  - pip install PyMySql

# install:
#   - ./setup.py install

script:
  - flake8 .
  - mysqladmin -u root create test_sh
  - cd tests
  - coverage run --include=*manuscripts/manuscripts* run_tests.py

after_success:
  - coveralls
